name: Blockifier-CI-Test

# TODO(Dori, 15/8/2024): Split this job, so the feature-less build doesn't run on every push to main
# branches.
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - auto_merge_enabled
      - edited
    paths:
      # Other than code-related changes, all changes related to the native-blockifier build-and-push
      # process should trigger the build (e.g., changes to the Dockerfile, build scripts, etc.).
      - ".github/workflows/blockifier_ci.yml"
      - "README.md"

# On PR events, cancel existing CI runs on this same PR for this workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  native-blockifier-artifacts-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Check if the user has the required permission to upload the artifact.
      - name: Get User Permission
        id: checkAccess
        uses: actions-cool/check-user-permission@v2
        with:
          require: write
          username: ${{ github.triggering_actor }}


      - name: Authenticate with GCS
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.NADIN_TEST_FORK_BUCKET_ACCESS_KEY }}
